import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#e1e2ed",
        "surface-variant": "#e1e2ed",
        "primary-fixed": "#dbe1ff",
        "on-surface": "#191b23",
        "surface-container-low": "#f3f3fe",
        "tertiary-fixed-dim": "#ffb596",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e7e7f3",
        "tertiary-container": "#bc4800",
        "on-tertiary-container": "#ffede6",
        "on-secondary-container": "#394c84",
        "on-primary-fixed-variant": "#003ea8",
        "secondary-fixed": "#dbe1ff",
        "surface-tint": "#0053db",
        "surface-container": "#ededf9",
        "on-primary": "#ffffff",
        surface: "#faf8ff",
        "on-tertiary-fixed": "#360f00",
        primary: "#004ac6",
        background: "#faf8ff",
        "on-secondary-fixed-variant": "#31447b",
        tertiary: "#943700",
        "secondary-container": "#acbfff",
        "on-error": "#ffffff",
        "inverse-primary": "#b4c5ff",
        error: "#ba1a1a",
        "on-surface-variant": "#434655",
        "inverse-surface": "#2e3039",
        "inverse-on-surface": "#f0f0fb",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#b4c5ff",
        "on-primary-fixed": "#00174b",
        "error-container": "#ffdad6",
        "surface-dim": "#d9d9e5",
        "outline-variant": "#c3c6d7",
        "surface-bright": "#faf8ff",
        secondary: "#495c95",
        "primary-container": "#2563eb",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#7d2d00",
        "on-secondary": "#ffffff",
        outline: "#737686",
        "on-primary-container": "#eeefff",
        "on-secondary-fixed": "#00174b",
        "tertiary-fixed": "#ffdbcd",
        "on-background": "#191b23",
        "primary-fixed-dim": "#b4c5ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "10px",
        xl: "12px",
        full: "9999px",
      },
      spacing: {
        "stack-xl": "32px",
        "stack-xs": "4px",
        "stack-lg": "24px",
        "stack-md": "16px",
        gutter: "24px",
        "stack-sm": "8px",
        "margin-mobile": "16px",
        "container-max": "1440px",
        "sidebar-width": "260px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-md-mobile": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-md-mobile": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
